services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pennbrook
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/seed

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./backend:/app
    command: go run main.go

volumes:
  postgres_data:

